// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwHQNlQo2uHqzkHiztcTsYYEaLl_G3CbU',
    appId: '1:929232019806:web:4b3e0cfe3da3454522efcf',
    messagingSenderId: '929232019806',
    projectId: 'ecommerce-c839b',
    authDomain: 'ecommerce-c839b.firebaseapp.com',
    storageBucket: 'ecommerce-c839b.appspot.com',
    measurementId: 'G-WWNWBJ1CTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApXH0vLB5uD0BpZY5claXbCErzlOmGP-Q',
    appId: '1:929232019806:android:a9e613f4b2eb594f22efcf',
    messagingSenderId: '929232019806',
    projectId: 'ecommerce-c839b',
    storageBucket: 'ecommerce-c839b.appspot.com',
  );
}
